Develop
siblis/cwc-back pull request #7
Opened 2018-11-12 19:00 UTC by pvgtag

2018-11-12 19:12 UTC, igorsimdyanov requested changes

2018-11-12 19:12 UTC, igorsimdyanov commented on Gemfile
> +gem 'faker'
Внутри блока нужен отступа в два пробела

2018-11-12 19:12 UTC, igorsimdyanov commented on app/controllers/api/v1/projects_controller.rb
> +      @projects = Project.order("id")
`"id"` лучше заменить на символ `:id` - выглядит лучше и обрабатывается быстрее.

2018-11-12 19:12 UTC, igorsimdyanov commented on app/controllers/api/v1/projects_controller.rb
> +    before_action :find_project, only: [:destroy, :show, :update]
Обычно массивы символов оформляют как %i[destroy show update]. Не настаиваю.

2018-11-13 04:09 UTC, pvgtag commented on Gemfile
> +gem 'faker'
А он есть в группе group :development, :test doю Это я пытался его на  Heroku запустить. Почему-то там при попытке вызвать Faker при заполнении БД ругается на непроинициализированную переменную.

2018-11-13 04:11 UTC, pvgtag commented on app/controllers/api/v1/projects_controller.rb
> +      @projects = Project.order("id")
Заменил

2018-11-13 04:15 UTC, pvgtag commented on app/controllers/api/v1/projects_controller.rb
> +    before_action :find_project, only: [:destroy, :show, :update]
поправил, пусть будет так, как общепринято

2018-11-13 04:42 UTC, closed without merging

2018-11-13 05:38 UTC, igorsimdyanov commented on Gemfile
> +gem 'faker'
На Heroku приложение не в продакшен режиме запускается? Может пока вообще вынести гем в глобальную default-область?